name: Build Templates

on:
  push:
    # paths:
    #   - 'screenpipe-tauri-template/'
    # branches:
    #   - main
    branches: [tauri-template-actions-development]
  pull_request:
    paths:
      - 'screenpipe-tauri-template/'
    # branches:
    #   - main
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  build_tauri_template:
    needs: checkout
    # runs-on: ubuntu-latest
    # steps:
    # - uses: actions/checkout@v4
    # - name: Calling workflow from screenpipe-tauri-template
    uses: ./screenpipe-tauri-template/.github/workflows/build.yml