on:
  push:
    paths:
      - 'screenpipe-tauri-template/'
    branches:
      - main
  pull_request:
    paths:
      - 'screenpipe-tauri-template/'
    branches:
      - main
jobs:
  build_tauri_template:
    uses: ./screenpipe-tauri-template/.github/workflows/build.yml