name: Build Templates

on:
  push:
    # paths:
    #   - 'screenpipe-tauri-template/'
    # branches:
    #   - main
  pull_request:
    paths:
      - 'screenpipe-tauri-template/'
    # branches:
    #   - main
jobs:
  build_tauri_template:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Calling workflow from screenpipe-tauri-template
      uses: ./screenpipe-tauri-template/.github/workflows/build.yml